-- Sadari MySQL 8.4 schema
-- Run this file against an already-created sadari database
-- User-side generated numeric keys use AUTO_INCREMENT from 1
-- Admin-side keys do not use sequences; the application assigns MAX(PK) + 1

SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE sadari;
SET FOREIGN_KEY_CHECKS = 0;

-- sadari.CT_NOTICE definition

CREATE TABLE `CT_NOTICE` (
  `NOTI_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '공지사항 주키',
  `VERS_NUMB` int NOT NULL COMMENT '공지사항 버전 부키',
  `CATE_CGRP` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '공지사항 카테고리 공통코드',
  `CATE_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '공지사항 카테고리 상세코드',
  `NOTI_TITL` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '공지사항 제목',
  `NOTI_ENTL` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '공지사항 영문 제목',
  `NOTI_CNTN` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '정제된 공지사항 HTML 본문',
  `NOTI_ENCT` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '정제된 공지사항 영문 HTML 본문',
  `TOPX_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '상단 고정 여부',
  `DPLY_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '현재 배포 여부',
  `REGI_ADMN` bigint NOT NULL COMMENT '등록 관리자 번호',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDT_ADMN` bigint DEFAULT NULL COMMENT '수정 관리자 번호',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  `DPLY_ADMN` bigint DEFAULT NULL COMMENT '배포 관리자 번호',
  `DPLY_DATE` datetime DEFAULT NULL COMMENT '배포 일시',
  PRIMARY KEY (`NOTI_NUMB`,`VERS_NUMB`),
  KEY `IX_CT_NOTICE_DPLY` (`DPLY_YSNO`,`TOPX_YSNO`,`DPLY_DATE`,`NOTI_NUMB`,`VERS_NUMB`),
  KEY `IX_CT_NOTICE_LATEST` (`NOTI_NUMB`,`VERS_NUMB`),
  KEY `IX_CT_NOTICE_CATE` (`CATE_CGRP`,`CATE_CODE`),
  CONSTRAINT `FK_CT_NOTICE_CATE` FOREIGN KEY (`CATE_CGRP`, `CATE_CODE`) REFERENCES `TB_CODEXD` (`COMM_CODE`, `COMD_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='버전형 공지사항';

-- sadari.CT_WLCMPG definition

CREATE TABLE `CT_WLCMPG` (
  `WLCM_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '웰컴페이지 주키',
  `VERS_NUMB` int NOT NULL COMMENT '웰컴페이지 버전 부키',
  `SUBX_TITL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '웰컴페이지 소제목',
  `SUBX_ENTL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '웰컴페이지 영문 소제목',
  `MAIN_TITL` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '웰컴페이지 제목',
  `MAIN_ENTL` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '웰컴페이지 영문 제목',
  `PAGE_DESC` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '웰컴페이지 설명',
  `PAGE_ENCT` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '웰컴페이지 영문 설명',
  `IMGE_URLX` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '웰컴페이지 이미지 공개 경로',
  `IMGE_ENUR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '웰컴페이지 영문 이미지 공개 경로',
  `SORT_ORDR` int NOT NULL COMMENT '노출 순서',
  `DPLY_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '현재 배포 여부',
  `REGI_ADMN` bigint NOT NULL COMMENT '등록 관리자 번호',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDT_ADMN` bigint DEFAULT NULL COMMENT '수정 관리자 번호',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  `DPLY_ADMN` bigint DEFAULT NULL COMMENT '배포 관리자 번호',
  `DPLY_DATE` datetime DEFAULT NULL COMMENT '배포 일시',
  PRIMARY KEY (`WLCM_NUMB`,`VERS_NUMB`),
  KEY `IX_CT_WLCMPG_DPLY` (`DPLY_YSNO`,`SORT_ORDR`,`WLCM_NUMB`,`VERS_NUMB`),
  KEY `IX_CT_WLCMPG_LATEST` (`WLCM_NUMB`,`VERS_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='버전형 웰컴페이지';

-- sadari.CT_SVINFO definition

CREATE TABLE `CT_SVINFO` (
  `CATE_CGRP` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '서비스 정보 카테고리 공통코드',
  `CATE_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '서비스 정보 카테고리 상세코드',
  `VERS_NUMB` int NOT NULL COMMENT '서비스 정보 버전 부키',
  `SVCI_TITL` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '서비스 정보 제목',
  `SVCI_ENTL` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '서비스 정보 영문 제목',
  `SVCI_CNTN` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '정제된 서비스 정보 HTML 본문',
  `SVCI_ENCT` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '정제된 서비스 정보 영문 HTML 본문',
  `DPLY_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '현재 배포 여부',
  `REGI_ADMN` bigint NOT NULL COMMENT '등록 관리자 번호',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDT_ADMN` bigint DEFAULT NULL COMMENT '수정 관리자 번호',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  `DPLY_ADMN` bigint DEFAULT NULL COMMENT '배포 관리자 번호',
  `DPLY_DATE` datetime DEFAULT NULL COMMENT '배포 일시',
  PRIMARY KEY (`CATE_CGRP`,`CATE_CODE`,`VERS_NUMB`),
  KEY `IX_CT_SVINFO_DPLY` (`DPLY_YSNO`,`DPLY_DATE`,`CATE_CODE`,`VERS_NUMB`),
  CONSTRAINT `FK_CT_SVINFO_CATE` FOREIGN KEY (`CATE_CGRP`, `CATE_CODE`) REFERENCES `TB_CODEXD` (`COMM_CODE`, `COMD_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='카테고리별 버전형 서비스 정보';

-- sadari.CT_POPUPX definition

CREATE TABLE `CT_POPUPX` (
  `POPU_SITU` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '팝업 사용 화면 코드',
  `POPU_CODE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '팝업 식별 코드',
  `MNGM_TITL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '관리 화면 제목',
  `CONT_FIRS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '첫 번째 콘텐츠 영역',
  `ENGL_FIRS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '첫 번째 영문 콘텐츠 영역',
  `CONT_SECO` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '두 번째 콘텐츠 영역',
  `ENGL_SECO` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '두 번째 영문 콘텐츠 영역',
  `CONT_THIR` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '세 번째 콘텐츠 영역',
  `ENGL_THIR` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '세 번째 영문 콘텐츠 영역',
  `CONT_FOUR` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '네 번째 콘텐츠 영역',
  `ENGL_FOUR` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '네 번째 영문 콘텐츠 영역',
  `REGI_ADMN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '등록 관리자 번호 또는 아이디',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDT_ADMN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '수정 관리자 번호 또는 아이디',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`POPU_SITU`,`POPU_CODE`),
  KEY `IX_CT_POPUPX_SITU` (`POPU_SITU`,`POPU_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 안내 팝업 콘텐츠';


-- sadari.TM_ALICON definition

CREATE TABLE `TM_ALICON` (
  `ALIM_SITU` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '알림 상황 코드',
  `MIME_TYPE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '아이콘 MIME 유형',
  `ICON_DATA` mediumblob NOT NULL COMMENT '알림 아이콘 바이너리',
  `FILE_SIZE` bigint NOT NULL COMMENT '아이콘 파일 크기(Byte)',
  `PIXL_WDTH` int NOT NULL COMMENT '아이콘 픽셀 너비',
  `PIXL_HGHT` int NOT NULL COMMENT '아이콘 픽셀 높이',
  `REGI_ADMN` bigint NOT NULL COMMENT '등록 관리자 번호',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDT_ADMN` bigint DEFAULT NULL COMMENT '수정 관리자 번호',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`ALIM_SITU`),
  KEY `FK_TM_ALICON_REGI` (`REGI_ADMN`),
  KEY `FK_TM_ALICON_UPDT` (`UPDT_ADMN`),
  CONSTRAINT `FK_TM_ALICON_REGI` FOREIGN KEY (`REGI_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`),
  CONSTRAINT `FK_TM_ALICON_UPDT` FOREIGN KEY (`UPDT_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='알림 아이콘 원본';


-- sadari.TB_ALTEMP definition

CREATE TABLE `TB_ALTEMP` (
  `ALIM_SITU` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '알림 상황 코드',
  `TEMP_CODE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '템플릿 코드',
  `TEMP_TITL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '템플릿 관리 제목',
  `ALIM_TITL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '알림 제목',
  `ALIM_ENTL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '알림 영문 제목',
  `TEMP_CONT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '템플릿 내용',
  `TEMP_ENCT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '템플릿 영문 내용',
  `USEE_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '사용 여부',
  `REGI_ADMN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '등록 관리자 번호 또는 아이디',
  `REGI_DATE` datetime DEFAULT NULL COMMENT '등록 일시',
  `UPDT_ADMN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '수정 관리자 번호 또는 아이디',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`ALIM_SITU`,`TEMP_CODE`),
  KEY `IX_TB_ALTEMP_USE` (`USEE_YSNO`,`ALIM_SITU`,`TEMP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='알림 템플릿';


-- sadari.TB_EVTBOX definition

CREATE TABLE `TB_EVTBOX` (
  `EVNT_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '이벤트 번호',
  `EVNT_TYPE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '이벤트 유형',
  `USER_NUMB` decimal(19,0) NOT NULL COMMENT '사용자 번호',
  `SPND_NUMB` decimal(19,0) NOT NULL COMMENT '회원 정지 이력 번호',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`EVNT_NUMB`),
  KEY `IX_TB_EVTBOX_TYPE` (`EVNT_TYPE`,`EVNT_NUMB`),
  KEY `IX_TB_EVTBOX_USER` (`USER_NUMB`,`EVNT_NUMB`),
  KEY `IX_TB_EVTBOX_SPND` (`SPND_NUMB`,`EVNT_NUMB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 상태 변경 Outbox 이벤트';


-- sadari.TB_NKSEQX definition

CREATE TABLE `TB_NKSEQX` (
  `SUBJ_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '주어 코드',
  `PRED_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '서술어 코드',
  `ANML_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '동물 명사 코드',
  `ISSU_YEAM` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '닉네임 발급 연월',
  `LAST_NUMB` int NOT NULL COMMENT '마지막 발급 번호',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`SUBJ_CODE`,`PRED_CODE`,`ANML_CODE`,`ISSU_YEAM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='닉네임 조합별 연월 순번';


-- sadari.TH_USSPND definition

CREATE TABLE `TH_USSPND` (
  `SPND_NUMB` bigint NOT NULL COMMENT '회원 정지 이력 번호',
  `USER_NUMB` decimal(19,0) NOT NULL COMMENT '사용자 번호',
  `PREV_STAT` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '처리 직전 사용자 상태',
  `SPND_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '회원 정지 유형',
  `SPND_RSON` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '회원 정지 사유 코드',
  `SPND_CNTN` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '관리자 내부 정지 사유',
  `SPND_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '회원 정지 처리 상태',
  `STRT_DATE` datetime NOT NULL COMMENT '시작 일시',
  `ENDX_DATE` datetime DEFAULT NULL COMMENT '종료 예정 일시',
  `RLES_DATE` datetime DEFAULT NULL COMMENT '해제 또는 만료 일시',
  `RLES_CNTN` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '관리자 내부 해제 사유',
  `REGI_ADMN` decimal(19,0) NOT NULL COMMENT '등록 관리자 번호 또는 아이디',
  `RLES_ADMN` decimal(19,0) DEFAULT NULL COMMENT '해제 관리자 번호',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDT_ADMN` decimal(19,0) DEFAULT NULL COMMENT '수정 관리자 번호 또는 아이디',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  `SYNC_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '사용자 상태 동기화 상태',
  `ACTV_USER` bigint GENERATED ALWAYS AS ((case when (`SPND_STAT` = _utf8mb4'ACTIVE') then `USER_NUMB` else NULL end)) STORED COMMENT '활성 정지 사용자 중복 방지 키',
  PRIMARY KEY (`SPND_NUMB`),
  UNIQUE KEY `UK_TH_USSPND_ACTV` (`ACTV_USER`),
  KEY `IX_TH_USSPND_USER` (`USER_NUMB`,`REGI_DATE` DESC,`SPND_NUMB` DESC),
  KEY `IX_TH_USSPND_STRT` (`STRT_DATE`,`USER_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='회원 이용 정지 이력';


-- sadari.TB_ALIMXX definition

CREATE TABLE `TB_ALIMXX` (
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `ALIM_NUMB` decimal(38,10) NOT NULL COMMENT '알림 번호',
  `ALIM_SITU` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '알림 상황 코드',
  `TEMP_CODE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '템플릿 코드',
  `ALIM_TITL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '알림 제목',
  `ALIM_CONT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '알림 내용',
  `TAGT_TYPE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '알림 이동 대상 유형',
  `TAGT_NUMB` bigint DEFAULT NULL COMMENT '알림 이동 대상 번호',
  `REPL_NUMB` bigint DEFAULT NULL COMMENT '알림 강조 댓글 번호',
  `CHAT_NUMB` bigint DEFAULT NULL COMMENT '알림 원본 채팅 번호',
  `READ_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '읽기 권한 또는 읽음 여부',
  `READ_DATE` datetime DEFAULT NULL COMMENT '읽음 처리 일시',
  `SEND_DATE` datetime DEFAULT NULL COMMENT '알림 발송 일시',
  `DELT_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '삭제 여부',
  PRIMARY KEY (`USER_NUMB`,`ALIM_NUMB`),
  KEY `FK_TB_ALIMXX_ALTEMP` (`ALIM_SITU`,`TEMP_CODE`),
  KEY `IX_TB_ALIMXX_USER` (`USER_NUMB`,`DELT_YSNO`,`SEND_DATE` DESC,`ALIM_NUMB` DESC),
  CONSTRAINT `FK_TB_ALIMXX_ALTEMP` FOREIGN KEY (`ALIM_SITU`, `TEMP_CODE`) REFERENCES `TB_ALTEMP` (`ALIM_SITU`, `TEMP_CODE`),
  CONSTRAINT `FK_TB_ALIMXX_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 알림 발송 내역';


-- sadari.TB_AUTHMN definition

CREATE TABLE `TB_AUTHMN` (
  `AUTH_CODE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '권한그룹 코드',
  `MENU_NUMB` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '상위 메뉴 번호',
  `SUBX_NUMB` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '하위 메뉴 번호',
  `READ_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '읽기 권한 또는 읽음 여부',
  `WRIT_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '쓰기 권한 여부',
  `DELT_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '삭제 여부',
  `REGI_ADMN` bigint DEFAULT NULL COMMENT '등록 관리자 번호 또는 아이디',
  `REGI_DATE` datetime(6) DEFAULT NULL COMMENT '등록 일시',
  `UPDT_ADMN` bigint DEFAULT NULL COMMENT '수정 관리자 번호 또는 아이디',
  `UPDT_DATE` datetime(6) DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`AUTH_CODE`,`MENU_NUMB`,`SUBX_NUMB`),
  KEY `FK_TB_AUTHMN_MENU` (`MENU_NUMB`,`SUBX_NUMB`),
  KEY `IX_TB_AUTHMN_AUTH` (`AUTH_CODE`,`MENU_NUMB`,`SUBX_NUMB`),
  KEY `FK_TB_AUTHMN_REGI` (`REGI_ADMN`),
  KEY `FK_TB_AUTHMN_UPDT` (`UPDT_ADMN`),
  CONSTRAINT `FK_TB_AUTHMN_AUTH` FOREIGN KEY (`AUTH_CODE`) REFERENCES `TM_AUTHXM` (`AUTH_CODE`),
  CONSTRAINT `FK_TB_AUTHMN_MENU` FOREIGN KEY (`MENU_NUMB`, `SUBX_NUMB`) REFERENCES `TM_ADMENU` (`MENU_NUMB`, `SUBX_NUMB`),
  CONSTRAINT `FK_TB_AUTHMN_REGI` FOREIGN KEY (`REGI_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`),
  CONSTRAINT `FK_TB_AUTHMN_UPDT` FOREIGN KEY (`UPDT_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='권한그룹별 관리자 메뉴 권한';


-- sadari.TB_CODEXD definition

CREATE TABLE `TB_CODEXD` (
  `COMM_CODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '공통코드',
  `COMD_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '세부코드',
  `COMD_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '세부코드 이름',
  `COMD_ENNM` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '세부코드 영문 이름',
  `CODE_EXPL` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '코드 설명',
  `UPPR_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '상위 세부코드',
  `OPT1_CODE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 1 코드',
  `OPT1_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 1 이름',
  `OPT1_ENNM` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 1 영문 이름',
  `OPT2_CODE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 2 코드',
  `OPT2_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 2 이름',
  `OPT2_ENNM` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 2 영문 이름',
  `OPT3_CODE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 3 코드',
  `OPT3_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 3 이름',
  `OPT3_ENNM` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 3 영문 이름',
  `OPT4_CODE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 4 코드',
  `OPT4_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 4 이름',
  `OPT4_ENNM` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '확장 속성 4 영문 이름',
  `USEE_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '사용 여부',
  `REGI_ADMN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '등록 관리자 번호 또는 아이디',
  `REGI_DATE` datetime DEFAULT NULL COMMENT '등록 일시',
  `SORT_ORDR` decimal(38,0) DEFAULT NULL COMMENT '정렬 순서',
  `UPDT_ADMN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '수정 관리자 번호 또는 아이디',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`COMM_CODE`,`COMD_CODE`),
  KEY `IX_TB_CODEXD_USE` (`COMM_CODE`,`USEE_YSNO`,`SORT_ORDR`),
  KEY `IX_TB_CODEXD_TREE` (`COMM_CODE`,`UPPR_CODE`,`SORT_ORDR`,`COMD_CODE`),
  CONSTRAINT `FK_TB_CODEXD_CODEXM` FOREIGN KEY (`COMM_CODE`) REFERENCES `TM_CODEXM` (`COMM_CODE`),
  CONSTRAINT `FK_TB_CODEXD_UPPR` FOREIGN KEY (`COMM_CODE`, `UPPR_CODE`) REFERENCES `TB_CODEXD` (`COMM_CODE`, `COMD_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='공통코드 세부 항목';

-- sadari.TB_FOLLOW definition

CREATE TABLE `TB_FOLLOW` (
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `FLOW_NUMB` bigint NOT NULL COMMENT '팔로우 대상 사용자 번호',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`USER_NUMB`,`FLOW_NUMB`),
  KEY `IX_TB_FOLLOW_FLOW` (`FLOW_NUMB`),
  KEY `IX_TB_FOLLOW_REGI` (`REGI_DATE`,`USER_NUMB`),
  CONSTRAINT `FK_FOLLOW_FLOW` FOREIGN KEY (`FLOW_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`),
  CONSTRAINT `FK_FOLLOW_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 팔로우 관계';


-- sadari.TB_USBLOC definition

CREATE TABLE `TB_USBLOC` (
  `USER_NUMB` bigint NOT NULL COMMENT '차단한 사용자 번호',
  `BLOC_NUMB` bigint NOT NULL COMMENT '차단 대상 사용자 번호',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  PRIMARY KEY (`USER_NUMB`,`BLOC_NUMB`),
  KEY `IX_TB_USBLOC_BLOC` (`BLOC_NUMB`,`USER_NUMB`),
  KEY `IX_TB_USBLOC_LIST` (`USER_NUMB`,`REGI_DATE` DESC,`BLOC_NUMB` DESC),
  CONSTRAINT `FK_TB_USBLOC_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_USBLOC_BLOC` FOREIGN KEY (`BLOC_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `CK_TB_USBLOC_SELF` CHECK ((`USER_NUMB` <> `BLOC_NUMB`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 차단 관계';


-- sadari.TB_LIKEXX definition

CREATE TABLE `TB_LIKEXX` (
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `TAGT_TYPE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '대상 유형',
  `TAGT_NUMB` bigint NOT NULL COMMENT '대상 번호',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`USER_NUMB`,`TAGT_TYPE`,`TAGT_NUMB`),
  KEY `FK_TB_LIKEXX_REPORT` (`TAGT_NUMB`),
  KEY `IX_TB_LIKEXX_TAGT` (`TAGT_TYPE`,`TAGT_NUMB`),
  KEY `IX_TB_LIKEXX_REGI` (`REGI_DATE`,`USER_NUMB`),
  CONSTRAINT `FK_TB_LIKEXX_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 좋아요 관계';


-- sadari.TB_LOGHIS definition

CREATE TABLE `TB_LOGHIS` (
  `LOGN_DATE` datetime(6) NOT NULL COMMENT '로그인 일시',
  `LOGN_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '로그인 이력 번호',
  `USER_NUMB` bigint DEFAULT NULL COMMENT '사용자 번호',
  `LOGN_IPXX` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '로그인 요청 IP 주소',
  `USER_AGNT` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '로그인 요청 User-Agent',
  `PROV_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '로그인 제공자 코드',
  PRIMARY KEY (`LOGN_NUMB`),
  KEY `IX_TB_LOGHIS_USER` (`USER_NUMB`,`LOGN_DATE` DESC),
  KEY `IX_TB_LOGHIS_DATE` (`LOGN_DATE`,`USER_NUMB`),
  CONSTRAINT `FK_LOGHIS_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 로그인 이력';


-- sadari.TB_PSHSUB definition

CREATE TABLE `TB_PSHSUB` (
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `ENDP_URLX` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '푸시 구독 엔드포인트',
  `P256_KEYX` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '푸시 암호화 공개 키',
  `AUTH_KEYX` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '푸시 인증 키',
  `USEE_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '사용 여부',
  `REGI_DATE` datetime DEFAULT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`USER_NUMB`,`ENDP_URLX`),
  KEY `IX_TB_PSHSUB_USER` (`USER_NUMB`,`USEE_YSNO`),
  CONSTRAINT `FK_TB_PSHSUB_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 웹 푸시 구독';


-- sadari.TB_RDATDX definition

CREATE TABLE `TB_RDATDX` (
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `READ_DATE` date NOT NULL COMMENT '독서 날짜',
  `READ_SECS` bigint NOT NULL DEFAULT 0 COMMENT '확정 독서 시간 초',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`USER_NUMB`,`READ_DATE`),
  KEY `IX_TB_RDATDX_DATE` (`READ_DATE`,`USER_NUMB`),
  CONSTRAINT `FK_TB_RDATDX_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 일별 독서 시간 집계';


-- sadari.TB_REPLXX definition

CREATE TABLE `TB_REPLXX` (
  `TAGT_TYPE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '댓글 대상 유형',
  `TAGT_NUMB` bigint NOT NULL COMMENT '댓글 대상 번호',
  `REPL_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '댓글 번호',
  `UPER_NUMB` bigint DEFAULT NULL COMMENT '상위 댓글 번호',
  `USER_NUMB` bigint DEFAULT NULL COMMENT '사용자 번호',
  `REPL_CNTN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '댓글 내용',
  `DELT_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '삭제 여부',
  `REGI_DATE` datetime DEFAULT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`TAGT_TYPE`,`TAGT_NUMB`,`REPL_NUMB`),
  UNIQUE KEY `UK_TB_REPLXX_NUMB` (`REPL_NUMB`),
  KEY `IX_TB_REPLXX_TAGT` (`TAGT_TYPE`,`TAGT_NUMB`,`UPER_NUMB`,`REGI_DATE` DESC),
  KEY `FK_TB_REPLXX_USER` (`USER_NUMB`),
  KEY `IX_TB_REPLXX_REGI` (`REGI_DATE`,`USER_NUMB`),
  CONSTRAINT `FK_TB_REPLXX_UPER` FOREIGN KEY (`TAGT_TYPE`, `TAGT_NUMB`, `UPER_NUMB`) REFERENCES `TB_REPLXX` (`TAGT_TYPE`, `TAGT_NUMB`, `REPL_NUMB`),
  CONSTRAINT `FK_TB_REPLXX_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='콘텐츠 댓글과 답글';


-- sadari.TL_SCLOGX definition

CREATE TABLE `TL_SCLOGX` (
  `RUNX_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '스케줄러 실행 번호',
  `SCHD_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '스케줄러 코드',
  `METH_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '실행 메서드 이름',
  `EXEC_STAT` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '실행 상태',
  `STRT_DATE` datetime(6) NOT NULL COMMENT '시작 일시',
  `FNSH_DATE` datetime(6) DEFAULT NULL COMMENT '실행 종료 일시',
  `TRGT_CNTT` bigint NOT NULL COMMENT '처리 대상 건수',
  `SUCC_CNTT` bigint NOT NULL COMMENT '성공 건수',
  `FAIL_CNTT` bigint NOT NULL COMMENT '실패 건수',
  `EXEC_MSEC` decimal(19,0) DEFAULT NULL COMMENT '실행 소요 밀리초',
  PRIMARY KEY (`RUNX_NUMB`),
  KEY `IX_TL_SCLOGX_CODE` (`SCHD_CODE`,`RUNX_NUMB` DESC)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='스케줄러 실행 로그';


-- sadari.TM_BKINFO definition

CREATE TABLE `TM_BKINFO` (
  `BOOK_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '도서 번호',
  `BOOK_ISBN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '도서 ISBN',
  `LANG_CODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'ko' COMMENT '도서 정보 언어 코드',
  `BOOK_TITL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '도서 제목',
  `BOOK_ATHR` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '도서 저자명',
  `BOOK_PUBL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '도서 출판사명',
  `BOOK_CVIM` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '도서 표지 이미지 URL',
  `BOOK_DESC` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '도서 설명',
  `PUBL_DATE` datetime DEFAULT NULL COMMENT '도서 출간일',
  PRIMARY KEY (`BOOK_NUMB`),
  UNIQUE KEY `UK_TM_BKINFO_ISBN_LANG` (`BOOK_ISBN`,`LANG_CODE`),
  CONSTRAINT `CK_TM_BKINFO_LANG` CHECK ((`LANG_CODE` in ('ko','en')))
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='도서 마스터';


-- sadari.TM_CODEXM definition

CREATE TABLE `TM_CODEXM` (
  `COMM_CODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '공통코드',
  `CODE_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '공통코드 이름',
  `CODE_EXPL` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '코드 설명',
  `USEE_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '사용 여부',
  `REGI_ADMN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '등록 관리자 번호 또는 아이디',
  `REGI_DATE` datetime DEFAULT NULL COMMENT '등록 일시',
  `UPDT_ADMN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '수정 관리자 번호 또는 아이디',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`COMM_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='공통코드 그룹';


-- sadari.TL_SCFAIL definition

CREATE TABLE `TL_SCFAIL` (
  `RUNX_NUMB` bigint NOT NULL COMMENT '스케줄러 실행 번호',
  `FAIL_NUMB` bigint NOT NULL COMMENT '실패 순번',
  `FAIL_TYPE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '실패 유형',
  `RSLT_CODE` bigint DEFAULT NULL COMMENT '처리 결과 코드',
  `RSLT_MESG` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '처리 결과 메시지',
  `ERRO_TYPE` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '오류 유형',
  `ERRO_CNTN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '오류 내용',
  `FAIL_DATE` datetime(6) NOT NULL COMMENT '실패 발생 일시',
  PRIMARY KEY (`RUNX_NUMB`,`FAIL_NUMB`),
  KEY `IX_TL_SCFAIL_RUNX` (`RUNX_NUMB`,`FAIL_NUMB`),
  CONSTRAINT `FK_TL_SCFAIL_LOG` FOREIGN KEY (`RUNX_NUMB`) REFERENCES `TL_SCLOGX` (`RUNX_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='스케줄러 실행 실패 상세';


-- sadari.TH_USWTHD definition

CREATE TABLE `TH_USWTHD` (
  `WTHD_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '계정 처리 이력 번호',
  `USER_NUMB` decimal(19,0) DEFAULT NULL COMMENT '사용자 번호',
  `USER_IDHS` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '탈퇴 시 보존하는 사용자 식별값 해시',
  `TYPE_CGRP` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'TYPE_CGRP 업무 데이터',
  `WTHD_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '계정 처리 유형',
  `RSON_CGRP` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'RSON_CGRP 업무 데이터',
  `WTHD_RSON` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '계정 처리 사유 코드',
  `RSON_CNTN` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '처리 사유 상세 내용',
  `STAT_CGRP` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'STAT_CGRP 업무 데이터',
  `WTHD_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '계정 처리 상태',
  `REQU_DATE` datetime NOT NULL COMMENT '처리 요청 일시',
  `DELT_DATE` datetime DEFAULT NULL COMMENT '삭제 예정 또는 처리 일시',
  `PROC_DATE` datetime DEFAULT NULL COMMENT '처리 완료 일시',
  `RCOV_DATE` datetime DEFAULT NULL COMMENT '복구 완료 일시',
  `ERRO_CNTN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '오류 내용',
  PRIMARY KEY (`WTHD_NUMB`),
  KEY `FK_TH_USWTHD_RSON` (`RSON_CGRP`,`WTHD_RSON`),
  KEY `FK_TH_USWTHD_STAT` (`STAT_CGRP`,`WTHD_STAT`),
  KEY `FK_TH_USWTHD_TYPE` (`TYPE_CGRP`,`WTHD_TYPE`),
  KEY `IX_TH_USWTHD_USER` (`USER_NUMB`,`WTHD_STAT`,`WTHD_NUMB` DESC),
  KEY `IX_TH_USWTHD_REQU` (`REQU_DATE`,`WTHD_TYPE`),
  KEY `IX_TH_USWTHD_RCOV` (`RCOV_DATE`,`USER_NUMB`),
  KEY `IX_TH_USWTHD_IDHS` (`USER_IDHS`,`USER_NUMB`),
  CONSTRAINT `FK_TH_USWTHD_RSON` FOREIGN KEY (`RSON_CGRP`, `WTHD_RSON`) REFERENCES `TB_CODEXD` (`COMM_CODE`, `COMD_CODE`),
  CONSTRAINT `FK_TH_USWTHD_STAT` FOREIGN KEY (`STAT_CGRP`, `WTHD_STAT`) REFERENCES `TB_CODEXD` (`COMM_CODE`, `COMD_CODE`),
  CONSTRAINT `FK_TH_USWTHD_TYPE` FOREIGN KEY (`TYPE_CGRP`, `WTHD_TYPE`) REFERENCES `TB_CODEXD` (`COMM_CODE`, `COMD_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='회원 계정 처리 이력';


-- sadari.TM_ADMENU definition

CREATE TABLE `TM_ADMENU` (
  `MENU_NUMB` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '상위 메뉴 번호',
  `SUBX_NUMB` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '하위 메뉴 번호',
  `MENU_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '메뉴 이름',
  `MENU_URLX` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '메뉴 URL',
  `SORT_ORDR` decimal(38,10) DEFAULT NULL COMMENT '정렬 순서',
  `USEE_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '사용 여부',
  `REGI_ADMN` bigint DEFAULT NULL COMMENT '등록 관리자 번호 또는 아이디',
  `REGI_DATE` datetime(6) DEFAULT NULL COMMENT '등록 일시',
  `UPDT_ADMN` bigint DEFAULT NULL COMMENT '수정 관리자 번호 또는 아이디',
  `UPDT_DATE` datetime(6) DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`MENU_NUMB`,`SUBX_NUMB`),
  KEY `IX_TM_ADMENU_USE` (`USEE_YSNO`,`SORT_ORDR`),
  KEY `FK_TM_ADMENU_REGI` (`REGI_ADMN`),
  KEY `FK_TM_ADMENU_UPDT` (`UPDT_ADMN`),
  CONSTRAINT `FK_TM_ADMENU_REGI` FOREIGN KEY (`REGI_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`),
  CONSTRAINT `FK_TM_ADMENU_UPDT` FOREIGN KEY (`UPDT_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='관리자 화면 메뉴';


-- sadari.TM_ADMINX definition

CREATE TABLE `TM_ADMINX` (
  `ADMN_NUMB` bigint NOT NULL COMMENT '관리자 번호',
  `ADMN_IDXX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '관리자 로그인 아이디',
  `PASS_WORD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '관리자 비밀번호 해시',
  `ADMN_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '관리자 이름',
  `AUTH_CODE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '권한그룹 코드',
  `DEPT_CODE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '부서 코드',
  `FAIL_CNTX` decimal(38,10) NOT NULL COMMENT '로그인 실패 횟수',
  `LGIN_DATE` datetime DEFAULT NULL COMMENT '관리자 마지막 로그인 일시',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`ADMN_NUMB`),
  UNIQUE KEY `UK_TM_ADMINX_IDXX` (`ADMN_IDXX`),
  KEY `IX_TM_ADMINX_AUTH` (`AUTH_CODE`,`ADMN_NUMB`),
  CONSTRAINT `FK_TM_ADMINX_AUTH` FOREIGN KEY (`AUTH_CODE`) REFERENCES `TM_AUTHXM` (`AUTH_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='관리자 계정';


-- sadari.TM_AUTHXM definition

CREATE TABLE `TM_AUTHXM` (
  `AUTH_CODE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '권한그룹 코드',
  `AUTH_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '권한그룹 이름',
  `USEE_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '사용 여부',
  `REGI_ADMN` bigint DEFAULT NULL COMMENT '등록 관리자 번호 또는 아이디',
  `REGI_DATE` datetime(6) DEFAULT NULL COMMENT '등록 일시',
  `UPDT_ADMN` bigint DEFAULT NULL COMMENT '수정 관리자 번호 또는 아이디',
  `UPDT_DATE` datetime(6) DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`AUTH_CODE`),
  KEY `FK_TM_AUTHXM_REGI` (`REGI_ADMN`),
  KEY `FK_TM_AUTHXM_UPDT` (`UPDT_ADMN`),
  CONSTRAINT `FK_TM_AUTHXM_REGI` FOREIGN KEY (`REGI_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`),
  CONSTRAINT `FK_TM_AUTHXM_UPDT` FOREIGN KEY (`UPDT_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='관리자 권한그룹';


-- sadari.TM_FILEXM definition

CREATE TABLE `TM_FILEXM` (
  `FILE_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '파일 번호',
  `ORIG_NAME` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '원본 파일명',
  `STOR_NAME` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '서버 저장 파일명',
  `FILE_PATH` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '파일 접근 경로',
  `FILE_SIZE` decimal(38,10) DEFAULT NULL COMMENT '파일 크기 바이트',
  `MIME_TYPE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '파일 MIME 유형',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  `REGI_USER` bigint DEFAULT NULL COMMENT '등록 사용자 번호',
  PRIMARY KEY (`FILE_NUMB`),
  KEY `IX_TM_FILEXM_STOR` (`STOR_NAME`),
  KEY `FK_FILEXM_REGI_USER` (`REGI_USER`),
  CONSTRAINT `FK_FILEXM_REGI_USER` FOREIGN KEY (`REGI_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='업로드 파일 메타 정보';


-- sadari.TM_GOALXM definition

CREATE TABLE `TM_GOALXM` (
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `GOAL_DATE` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '목표 적용 기간',
  `GOAL_TYPE` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '목표 유형',
  `GOAL_CNTT` decimal(38,10) DEFAULT NULL COMMENT '목표 독서 권수',
  `REGI_DATE` datetime DEFAULT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
  `UPDT_CNTT` decimal(38,0) DEFAULT NULL COMMENT '하향 수정 횟수',
  PRIMARY KEY (`USER_NUMB`,`GOAL_DATE`,`GOAL_TYPE`),
  CONSTRAINT `FK_TM_GOALXM_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 기간별 독서 목표';


-- sadari.TM_REPORT definition

CREATE TABLE `TM_REPORT` (
  `REPT_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '독후감 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `BOOK_NUMB` bigint NOT NULL COMMENT '도서 번호',
  `LANG_CODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'ko' COMMENT '독후감 작성 언어 코드',
  `REPT_STAT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '독서 상태 코드',
  `REPT_STDT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '독서 시작일',
  `REPT_ENDT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '독서 종료일 또는 목표 종료일',
  `REPT_GRDE` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '도서 평점',
  `REPT_COLR` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '책장 표시 색상 코드',
  `REPT_CNTN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '독후감 내용',
  `PUBC_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '공개 여부',
  `LKAL_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '독후감 좋아요 알림 여부',
  `RPAL_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '독후감 댓글 알림 여부',
  `PUBC_DATE` datetime(6) DEFAULT NULL COMMENT '최초 공개 일시',
  `REGI_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`REPT_NUMB`),
  KEY `IX_TM_REPORT_USER` (`USER_NUMB`,`REPT_ENDT`(191),`REPT_NUMB`),
  KEY `IX_TM_REPORT_BOOK` (`BOOK_NUMB`),
  KEY `IX_TM_REPORT_REGI` (`REGI_DATE`,`USER_NUMB`),
  KEY `IX_TM_REPORT_FEED` (`USER_NUMB`,`PUBC_YSNO`,`PUBC_DATE` DESC,`REPT_NUMB` DESC),
  CONSTRAINT `FK_TM_REPORT_BOOK` FOREIGN KEY (`BOOK_NUMB`) REFERENCES `TM_BKINFO` (`BOOK_NUMB`),
  CONSTRAINT `FK_TM_REPORT_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`),
  CONSTRAINT `CK_TM_REPORT_LANG` CHECK ((`LANG_CODE` in ('ko','en'))),
  CONSTRAINT `CK_TM_REPORT_LKAL` CHECK ((`LKAL_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_REPORT_RPAL` CHECK ((`RPAL_YSNO` in ('Y','N')))
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 독후감';


-- sadari.TB_REPTRN definition

CREATE TABLE `TB_REPTRN` (
  `REPT_NUMB` bigint NOT NULL COMMENT '독후감 번호',
  `LANG_CODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '번역 대상 언어 코드',
  `ORIG_HASH` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '번역 기준 원문 SHA-256 해시',
  `TRNS_CNTN` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '독후감 번역 내용',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '수정 일시',
  PRIMARY KEY (`REPT_NUMB`,`LANG_CODE`),
  CONSTRAINT `FK_TB_REPTRN_REPT` FOREIGN KEY (`REPT_NUMB`) REFERENCES `TM_REPORT` (`REPT_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `CK_TB_REPTRN_LANG` CHECK ((`LANG_CODE` in ('ko','en')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독후감 번역 캐시';


-- sadari.TM_RDTMRX definition

CREATE TABLE `TM_RDTMRX` (
  `TMRX_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '독서 타이머 세션 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `REPT_NUMB` bigint DEFAULT NULL COMMENT '연결 독후감 번호',
  `TMRX_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '독서 타이머 상태 코드',
  `TARG_SECS` bigint DEFAULT NULL COMMENT '알림 목표 독서 시간 초',
  `READ_SECS` bigint NOT NULL DEFAULT 0 COMMENT '확정 독서 시간 초',
  `ALRM_DATE` datetime(6) DEFAULT NULL COMMENT '목표시간 알림 예정 일시',
  `SEND_DATE` datetime(6) DEFAULT NULL COMMENT '목표시간 알림 발송 일시',
  `STRT_DATE` datetime(6) NOT NULL COMMENT '세션 시작 일시',
  `LAST_STRT` datetime(6) DEFAULT NULL COMMENT '최근 측정 시작 일시',
  `ENDX_DATE` datetime(6) DEFAULT NULL COMMENT '세션 완료 일시',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`TMRX_NUMB`),
  KEY `IX_TM_RDTMRX_ACTIVE` (`USER_NUMB`,`TMRX_STAT`,`STRT_DATE`),
  KEY `IX_TM_RDTMRX_ALRM` (`TMRX_STAT`,`SEND_DATE`,`ALRM_DATE`,`TMRX_NUMB`),
  KEY `IX_TM_RDTMRX_ENDX` (`ENDX_DATE`,`USER_NUMB`),
  KEY `IX_TM_RDTMRX_REPT` (`REPT_NUMB`),
  CONSTRAINT `FK_TM_RDTMRX_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`),
  CONSTRAINT `FK_TM_RDTMRX_REPT` FOREIGN KEY (`REPT_NUMB`) REFERENCES `TM_REPORT` (`REPT_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 독서 타이머 세션';


-- sadari.TM_URMENU definition

CREATE TABLE `TM_URMENU` (
  `MENU_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '메뉴 번호',
  `PARN_NUMB` bigint DEFAULT NULL COMMENT '상위 메뉴 번호',
  `MENU_LEVL` tinyint NOT NULL COMMENT '메뉴 단계',
  `MENU_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '메뉴 이름',
  `MENU_ENNM` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '메뉴 영문 이름',
  `MENU_URLX` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '메뉴 URL',
  `SORT_ORDR` decimal(38,10) DEFAULT NULL COMMENT '정렬 순서',
  `SHOW_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '화면 노출 여부',
  `USEE_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '사용 여부',
  `REGI_ADMN` bigint DEFAULT NULL COMMENT '등록 관리자 번호 또는 아이디',
  `REGI_DATE` datetime(6) DEFAULT NULL COMMENT '등록 일시',
  `UPDT_ADMN` bigint DEFAULT NULL COMMENT '수정 관리자 번호 또는 아이디',
  `UPDT_DATE` datetime(6) DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`MENU_NUMB`),
  KEY `IX_TM_URMENU_TREE` (`PARN_NUMB`,`SORT_ORDR`,`MENU_NUMB`),
  KEY `IX_TM_URMENU_SHOW` (`SHOW_YSNO`,`USEE_YSNO`,`PARN_NUMB`,`SORT_ORDR`),
  KEY `FK_TM_URMENU_REGI` (`REGI_ADMN`),
  KEY `FK_TM_URMENU_UPDT` (`UPDT_ADMN`),
  CONSTRAINT `CK_TM_URMENU_LEVL` CHECK ((`MENU_LEVL` between 1 and 3)),
  CONSTRAINT `FK_TM_URMENU_PARN` FOREIGN KEY (`PARN_NUMB`) REFERENCES `TM_URMENU` (`MENU_NUMB`) ON DELETE RESTRICT,
  CONSTRAINT `FK_TM_URMENU_REGI` FOREIGN KEY (`REGI_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`),
  CONSTRAINT `FK_TM_URMENU_UPDT` FOREIGN KEY (`UPDT_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 화면 메뉴';


-- sadari.TM_USERXM definition

CREATE TABLE `TM_USERXM` (
  `USER_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '사용자 번호',
  `PROF_NUMB` bigint DEFAULT NULL COMMENT '프로필 이미지 파일 번호',
  `BGIM_NUMB` bigint DEFAULT NULL COMMENT '배경 이미지 파일 번호',
  `PROF_DATE` datetime(6) DEFAULT NULL COMMENT '프로필 이미지 변경 일시',
  `BGIM_DATE` datetime(6) DEFAULT NULL COMMENT '배경 이미지 변경 일시',
  `USER_IDXX` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'OAuth 사용자 식별값 암호문',
  `USER_NICK` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '사용자 닉네임',
  `USER_PROV` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '로그인 제공자 코드',
  `USER_ROLE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '사용자 권한 코드',
  `INTR_CNTN` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '프로필 한줄소개',
  `JOIN_DATE` datetime NOT NULL COMMENT '회원 가입 일시',
  `USER_CGRP` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'USER_CGRP 업무 데이터',
  `USER_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '사용자 계정 상태',
  `WTHD_DATE` datetime DEFAULT NULL COMMENT '계정 비활성화 일시',
  `DELT_DATE` datetime DEFAULT NULL COMMENT '삭제 예정 또는 처리 일시',
  `ONBD_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '온보딩 완료 여부',
  PRIMARY KEY (`USER_NUMB`),
  UNIQUE KEY `UK_TM_USERXM_IDXX` (`USER_IDXX`),
  UNIQUE KEY `UK_TM_USERXM_NICK` (`USER_NICK`),
  KEY `FK_TM_USERXM_STAT` (`USER_CGRP`,`USER_STAT`),
  KEY `IX_TM_USERXM_NICK` (`USER_NICK`),
  KEY `IX_TM_USERXM_STAT` (`USER_STAT`,`USER_NUMB`),
  KEY `IX_TM_USERXM_JOIN` (`JOIN_DATE`,`USER_NUMB`),
  KEY `IX_TM_USERXM_PROF_FEED` (`USER_STAT`,`PROF_DATE` DESC,`USER_NUMB`),
  KEY `IX_TM_USERXM_BGIM_FEED` (`USER_STAT`,`BGIM_DATE` DESC,`USER_NUMB`),
  KEY `FK_TM_USERXM_BGIM` (`BGIM_NUMB`),
  KEY `FK_TM_USERXM_PROF` (`PROF_NUMB`),
  CONSTRAINT `FK_TM_USERXM_BGIM` FOREIGN KEY (`BGIM_NUMB`) REFERENCES `TM_FILEXM` (`FILE_NUMB`),
  CONSTRAINT `FK_TM_USERXM_PROF` FOREIGN KEY (`PROF_NUMB`) REFERENCES `TM_FILEXM` (`FILE_NUMB`),
  CONSTRAINT `FK_TM_USERXM_STAT` FOREIGN KEY (`USER_CGRP`, `USER_STAT`) REFERENCES `TB_CODEXD` (`COMM_CODE`, `COMD_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 계정과 프로필';


-- sadari.TM_USSETX definition

CREATE TABLE `TM_USSETX` (
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `ENGL_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '영문 사용 여부',
  `RSTA_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '독서 통계 공개 여부',
  `GOAL_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '독서 목표 공개 여부',
  `IMFD_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '사진 변경 피드 공개 여부',
  `RPUB_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '신규 독후감 공개 기본값',
  `LKAL_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '좋아요 알림 사용 여부',
  `RPAL_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '댓글과 답글 알림 사용 여부',
  `FOLL_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '팔로우 알림 사용 여부',
  `CLUB_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '선택형 독서 모임 알림 사용 여부',
  `CHAT_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '독서 모임 채팅 알림 사용 여부',
  `RDUE_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '독후감 목표 종료 알림 사용 여부',
  `LKDF_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '신규 독후감 좋아요 알림 기본값',
  `RPDF_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '신규 독후감 댓글 알림 기본값',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`USER_NUMB`),
  CONSTRAINT `FK_TM_USSETX_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`),
  CONSTRAINT `CK_TM_USSETX_ENGL` CHECK ((`ENGL_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_RSTA` CHECK ((`RSTA_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_GOAL` CHECK ((`GOAL_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_IMFD` CHECK ((`IMFD_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_RPUB` CHECK ((`RPUB_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_LKAL` CHECK ((`LKAL_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_RPAL` CHECK ((`RPAL_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_FOLL` CHECK ((`FOLL_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_CLUB` CHECK ((`CLUB_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_CHAT` CHECK ((`CHAT_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_RDUE` CHECK ((`RDUE_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_LKDF` CHECK ((`LKDF_YSNO` in ('Y','N'))),
  CONSTRAINT `CK_TM_USSETX_RPDF` CHECK ((`RPDF_YSNO` in ('Y','N')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='회원별 서비스 설정';


-- sadari.TB_USVIEW definition

CREATE TABLE `TB_USVIEW` (
  `VIEW_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '조회 대상 유형',
  `TAGT_NUMB` bigint NOT NULL COMMENT '조회 대상 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '최초 조회 일시',
  PRIMARY KEY (`VIEW_TYPE`,`TAGT_NUMB`,`USER_NUMB`),
  KEY `IX_TB_USVIEW_USER` (`USER_NUMB`,`VIEW_TYPE`,`TAGT_NUMB`),
  CONSTRAINT `FK_TB_USVIEW_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 콘텐츠 조회 이력';


-- sadari.TB_USINTR definition

CREATE TABLE `TB_USINTR` (
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `INTR_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'CATE_CODE 하위 관심분야 세부코드',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`USER_NUMB`,`INTR_CODE`),
  KEY `IX_TB_USINTR_RECM` (`INTR_CODE`,`USER_NUMB`),
  CONSTRAINT `FK_TB_USINTR_01` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='회원 독서 관심분야';


-- sadari.TM_CLUBXM definition

CREATE TABLE `TM_CLUBXM` (
  `CLUB_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '모임 번호',
  `OWNR_NUMB` bigint DEFAULT NULL COMMENT '현재 모임장 사용자 번호',
  `CLUB_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '모임명',
  `CLUB_CNTN` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '모임 소개',
  `CLUB_VISB` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '모임 공개 범위',
  `JOIN_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '가입 방식',
  `CLUB_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '모임 운영 상태',
  `RCRT_YSNO` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '신규 회원 모집 가능 여부',
  `MAXX_MEMB` int NOT NULL COMMENT '최대 회원 수',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  `CLOS_DATE` datetime(6) DEFAULT NULL COMMENT '종료 일시',
  PRIMARY KEY (`CLUB_NUMB`),
  KEY `IX_TM_CLUBXM_FIND` (`CLUB_VISB`,`CLUB_STAT`,`REGI_DATE`,`CLUB_NUMB`),
  KEY `IX_TM_CLUBXM_OWNR` (`OWNR_NUMB`,`CLUB_STAT`,`CLUB_NUMB`),
  CONSTRAINT `FK_TM_CLUBXM_01` FOREIGN KEY (`OWNR_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 마스터';

-- sadari.TH_CLADMN definition

CREATE TABLE `TH_CLADMN` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `HIST_NUMB` bigint NOT NULL COMMENT '모임별 관리자 조치 이력 번호',
  `ADMN_NUMB` bigint NOT NULL COMMENT '조치 관리자 번호',
  `ACTN_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '관리자 모임 조치 유형',
  `BEFR_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '조치 전 모임 상태',
  `AFTR_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '조치 후 모임 상태',
  `ACTN_RSON` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '관리자 조치 사유',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '조치 일시',
  PRIMARY KEY (`CLUB_NUMB`,`HIST_NUMB`),
  KEY `IX_TH_CLADMN_ADMN` (`ADMN_NUMB`,`REGI_DATE`,`CLUB_NUMB`),
  CONSTRAINT `FK_TH_CLADMN_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TH_CLADMN_02` FOREIGN KEY (`ADMN_NUMB`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='관리자 독서 모임 조치 이력';

-- sadari.TB_CLCATE definition

CREATE TABLE `TB_CLCATE` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `INTR_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'CATE_CODE 하위 관심분야 세부코드',
  `SORT_ORDR` tinyint NOT NULL COMMENT '모임 카테고리 노출 순서와 대표 카테고리 구분',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`CLUB_NUMB`,`INTR_CODE`),
  UNIQUE KEY `UK_TB_CLCATE_SORT` (`CLUB_NUMB`,`SORT_ORDR`),
  KEY `IX_TB_CLCATE_RECM` (`INTR_CODE`,`CLUB_NUMB`),
  CONSTRAINT `FK_TB_CLCATE_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 카테고리';

-- sadari.TB_CLMEMX definition

CREATE TABLE `TB_CLMEMX` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '사용자 번호',
  `MEMB_ROLE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '모임원 역할',
  `MEMB_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '모임원 또는 초대 상태',
  `SEND_NUMB` bigint DEFAULT NULL COMMENT '초대를 발송한 모임장 사용자 번호',
  `INVT_DATE` datetime(6) DEFAULT NULL COMMENT '초대 발송 일시',
  `EXPR_DATE` datetime(6) DEFAULT NULL COMMENT '초대 만료 일시',
  `JOIN_DATE` datetime(6) DEFAULT NULL COMMENT '가입 확정 일시',
  `READ_NUMB` bigint DEFAULT NULL COMMENT '마지막으로 읽은 채팅 메시지 번호',
  `EXIT_DATE` datetime(6) DEFAULT NULL COMMENT '모임 탈퇴 또는 퇴장 일시',
  `BLOC_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '재가입 차단 여부',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`CLUB_NUMB`,`USER_NUMB`),
  KEY `IX_TB_CLMEMX_USER` (`USER_NUMB`,`MEMB_STAT`,`CLUB_NUMB`),
  KEY `IX_TB_CLMEMX_CLUB` (`CLUB_NUMB`,`MEMB_STAT`,`USER_NUMB`),
  KEY `IX_TB_CLMEMX_SEAT` (`CLUB_NUMB`,`MEMB_STAT`,`EXPR_DATE`),
  KEY `FK_TB_CLMEMX_SEND` (`SEND_NUMB`),
  CONSTRAINT `FK_TB_CLMEMX_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_CLMEMX_02` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_CLMEMX_03` FOREIGN KEY (`SEND_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 회원과 초대 예약석';

-- sadari.TM_CLCHAT definition

CREATE TABLE `TM_CLCHAT` (
  `CHAT_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '채팅 메시지 번호',
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `USER_NUMB` bigint DEFAULT NULL COMMENT '사용자 번호',
  `CHAT_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '채팅 메시지 유형',
  `CHAT_CNTN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '채팅 메시지 본문',
  `CLNT_UUID` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '클라이언트 메시지 식별값',
  `DELT_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 일시',
  PRIMARY KEY (`CHAT_NUMB`),
  UNIQUE KEY `UK_TM_CLCHAT_UUID` (`CLUB_NUMB`,`CLNT_UUID`),
  KEY `IX_TM_CLCHAT_CLUB` (`CLUB_NUMB`,`CHAT_NUMB`),
  KEY `IX_TM_CLCHAT_USER` (`USER_NUMB`,`CHAT_NUMB`),
  CONSTRAINT `CK_TM_CLCHAT_DELT` CHECK (`DELT_YSNO` IN ('Y','N')),
  CONSTRAINT `FK_TM_CLCHAT_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TM_CLCHAT_02` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='모임 채팅';

-- sadari.TH_CLKICK definition

CREATE TABLE `TH_CLKICK` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `KICK_NUMB` bigint NOT NULL COMMENT '강제 퇴장 이력 번호',
  `USER_NUMB` bigint DEFAULT NULL COMMENT '사용자 번호',
  `PROC_USER` bigint DEFAULT NULL COMMENT '처리 사용자 번호',
  `KICK_RSON` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '강제 퇴장 사유',
  `KICK_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '강제 퇴장 일시',
  `RLES_DATE` datetime(6) DEFAULT NULL COMMENT '재가입 차단 해제 일시',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  PRIMARY KEY (`CLUB_NUMB`,`KICK_NUMB`),
  KEY `IX_TH_CLKICK_USER` (`USER_NUMB`,`KICK_DATE`,`CLUB_NUMB`),
  KEY `IX_TH_CLKICK_PROC` (`PROC_USER`,`KICK_DATE`,`CLUB_NUMB`),
  CONSTRAINT `FK_TH_CLKICK_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TH_CLKICK_02` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL,
  CONSTRAINT `FK_TH_CLKICK_03` FOREIGN KEY (`PROC_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='모임원 강제 퇴장 이력';

-- sadari.TB_CLQUES definition

CREATE TABLE `TB_CLQUES` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `QUES_FIRS` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '첫 번째 가입 질문',
  `QUES_SECO` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '두 번째 가입 질문',
  `QUES_THIR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '세 번째 가입 질문',
  `QUES_FOUR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '네 번째 가입 질문',
  `QUES_FIFT` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '다섯 번째 가입 질문',
  `REGI_USER` bigint DEFAULT NULL COMMENT '등록 사용자 번호',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_USER` bigint DEFAULT NULL COMMENT '수정 사용자 번호',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`CLUB_NUMB`),
  KEY `FK_TB_CLQUES_REGI` (`REGI_USER`),
  KEY `FK_TB_CLQUES_UPDT` (`UPDT_USER`),
  CONSTRAINT `FK_TB_CLQUES_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_CLQUES_02` FOREIGN KEY (`REGI_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL,
  CONSTRAINT `FK_TB_CLQUES_03` FOREIGN KEY (`UPDT_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 가입 질문';

-- sadari.TB_CLJOIN definition

CREATE TABLE `TB_CLJOIN` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `APPL_NUMB` bigint NOT NULL COMMENT '모임별 가입 신청 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '가입 신청 사용자 번호',
  `QUES_FIRS` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '첫 번째 가입 질문 사본',
  `QUES_SECO` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '두 번째 가입 질문 사본',
  `QUES_THIR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '세 번째 가입 질문 사본',
  `QUES_FOUR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '네 번째 가입 질문 사본',
  `QUES_FIFT` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '다섯 번째 가입 질문 사본',
  `ANSR_FIRS` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '처리 전 첫 번째 가입 답변',
  `ANSR_SECO` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '처리 전 두 번째 가입 답변',
  `ANSR_THIR` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '처리 전 세 번째 가입 답변',
  `ANSR_FOUR` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '처리 전 네 번째 가입 답변',
  `ANSR_FIFT` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '처리 전 다섯 번째 가입 답변',
  `JOIN_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '가입 신청 상태',
  `APPL_DATE` datetime(6) NOT NULL COMMENT '가입 신청 일시',
  `PROC_USER` bigint DEFAULT NULL COMMENT '가입 신청 처리 사용자 번호',
  `PROC_DATE` datetime(6) DEFAULT NULL COMMENT '가입 신청 처리 일시',
  PRIMARY KEY (`CLUB_NUMB`,`APPL_NUMB`),
  KEY `IX_TB_CLJOIN_USER` (`CLUB_NUMB`,`USER_NUMB`,`JOIN_STAT`),
  KEY `IX_TB_CLJOIN_MINE` (`USER_NUMB`,`JOIN_STAT`,`APPL_DATE`),
  KEY `FK_TB_CLJOIN_PROC` (`PROC_USER`),
  CONSTRAINT `FK_TB_CLJOIN_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_CLJOIN_02` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_CLJOIN_03` FOREIGN KEY (`PROC_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 승인 가입 신청';

-- sadari.TM_CLRNDX definition

CREATE TABLE `TB_CLBREC` (
  `RECM_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '추천 번호',
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `BOOK_NUMB` bigint NOT NULL COMMENT '도서 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '추천 사용자 번호',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  PRIMARY KEY (`RECM_NUMB`),
  KEY `IX_TB_CLBREC_BOOK` (`CLUB_NUMB`,`BOOK_NUMB`),
  KEY `IX_TB_CLBREC_USER` (`USER_NUMB`,`CLUB_NUMB`),
  CONSTRAINT `FK_TB_CLBREC_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_CLBREC_02` FOREIGN KEY (`BOOK_NUMB`) REFERENCES `TM_BKINFO` (`BOOK_NUMB`),
  CONSTRAINT `FK_TB_CLBREC_03` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 다음 도서 추천';

CREATE TABLE `TB_CLBVOT` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '투표 사용자 번호',
  `RECM_NUMB` bigint NOT NULL COMMENT '추천 번호',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '수정 일시',
  PRIMARY KEY (`CLUB_NUMB`,`USER_NUMB`,`RECM_NUMB`),
  KEY `IX_TB_CLBVOT_RECM` (`RECM_NUMB`,`CLUB_NUMB`),
  CONSTRAINT `FK_TB_CLBVOT_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_CLBVOT_02` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_CLBVOT_03` FOREIGN KEY (`RECM_NUMB`) REFERENCES `TB_CLBREC` (`RECM_NUMB`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 다음 도서 투표';

-- sadari.TM_CLOWNX definition

CREATE TABLE `TM_CLOWNX` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `ELCT_NUMB` bigint NOT NULL COMMENT '모임별 모임장 선거 번호',
  `PREV_OWNR` bigint DEFAULT NULL COMMENT '기존 모임장 사용자 번호 감사값',
  `ABSN_RSON` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '모임장 확정 부재 사유',
  `EVID_CNTN` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '모임장 확정 부재 근거 내용',
  `SELT_NUMB` bigint DEFAULT NULL COMMENT '도서 미확정 사유의 선정 번호',
  `ELCT_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '모임장 선거 상태',
  `EXTN_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '선거 기간 연장 여부',
  `STRT_DATE` datetime(6) NOT NULL COMMENT '선거 시작 일시',
  `ENDX_DATE` datetime(6) NOT NULL COMMENT '선거 마감 일시',
  `RSLT_USER` bigint DEFAULT NULL COMMENT '당선 사용자 번호',
  `CNFM_ADMN` bigint DEFAULT NULL COMMENT '부재 사유 확정 관리자 번호',
  `IDEM_KEYX` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '선거 생성 멱등키',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`CLUB_NUMB`,`ELCT_NUMB`),
  UNIQUE KEY `UK_TM_CLOWNX_IDEM` (`CLUB_NUMB`,`IDEM_KEYX`),
  KEY `IX_TM_CLOWNX_STAT` (`CLUB_NUMB`,`ELCT_STAT`,`ENDX_DATE`),
  KEY `FK_TM_CLOWNX_RSLT` (`RSLT_USER`),
  KEY `FK_TM_CLOWNX_ADMN` (`CNFM_ADMN`),
  CONSTRAINT `CK_TM_CLOWNX_EXTN` CHECK (`EXTN_YSNO` IN ('Y','N')),
  CONSTRAINT `CK_TM_CLOWNX_DATE` CHECK (`ENDX_DATE` > `STRT_DATE`),
  CONSTRAINT `FK_TM_CLOWNX_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TM_CLOWNX_02` FOREIGN KEY (`RSLT_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL,
  CONSTRAINT `FK_TM_CLOWNX_03` FOREIGN KEY (`CNFM_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 모임장 선거';

-- sadari.TM_CLVOTX definition

CREATE TABLE `TM_CLVOTX` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `VOTE_NUMB` bigint NOT NULL COMMENT '모임별 투표 번호',
  `VOTE_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '도서 또는 모임장 투표 유형',
  `VOTE_ROUN` tinyint NOT NULL DEFAULT '1' COMMENT '본선 또는 결선 투표 차수',
  `PRNT_VOTE` bigint DEFAULT NULL COMMENT '결선의 원 투표 번호',
  `SELT_NUMB` bigint DEFAULT NULL COMMENT '도서 선정 번호',
  `ELCT_NUMB` bigint DEFAULT NULL COMMENT '모임장 선거 번호',
  `VOTE_TITL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '투표 제목 스냅샷',
  `VOTE_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '투표 상태',
  `SECR_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '비밀투표 여부',
  `CHNG_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '마감 전 투표 변경 허용 여부',
  `STRT_DATE` datetime(6) NOT NULL COMMENT '투표 시작 일시',
  `ENDX_DATE` datetime(6) NOT NULL COMMENT '투표 마감 일시',
  `RSLT_NUMB` bigint DEFAULT NULL COMMENT '선정 도서 또는 당선 사용자 번호',
  `CLOS_DATE` datetime(6) DEFAULT NULL COMMENT '투표 종료 일시',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`CLUB_NUMB`,`VOTE_NUMB`),
  UNIQUE KEY `UK_TM_CLVOTX_SELT` (`CLUB_NUMB`,`SELT_NUMB`,`VOTE_ROUN`),
  UNIQUE KEY `UK_TM_CLVOTX_ELCT` (`CLUB_NUMB`,`ELCT_NUMB`,`VOTE_ROUN`),
  KEY `IX_TM_CLVOTX_PRNT` (`CLUB_NUMB`,`PRNT_VOTE`),
  KEY `IX_TM_CLVOTX_STAT` (`CLUB_NUMB`,`VOTE_TYPE`,`VOTE_STAT`,`ENDX_DATE`),
  CONSTRAINT `CK_TM_CLVOTX_TYPE` CHECK ((`VOTE_TYPE` = 'BOOK' AND `SELT_NUMB` IS NOT NULL AND `ELCT_NUMB` IS NULL) OR (`VOTE_TYPE` = 'OWNER' AND `SELT_NUMB` IS NULL AND `ELCT_NUMB` IS NOT NULL)),
  CONSTRAINT `CK_TM_CLVOTX_ROUN` CHECK ((`VOTE_ROUN` = 1 AND `PRNT_VOTE` IS NULL) OR (`VOTE_ROUN` = 2 AND `PRNT_VOTE` IS NOT NULL)),
  CONSTRAINT `CK_TM_CLVOTX_SECR` CHECK (`SECR_YSNO` IN ('Y','N')),
  CONSTRAINT `CK_TM_CLVOTX_CHNG` CHECK (`CHNG_YSNO` IN ('Y','N')),
  CONSTRAINT `CK_TM_CLVOTX_DATE` CHECK (`ENDX_DATE` > `STRT_DATE`),
  CONSTRAINT `FK_TM_CLVOTX_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TM_CLVOTX_02` FOREIGN KEY (`CLUB_NUMB`,`PRNT_VOTE`) REFERENCES `TM_CLVOTX` (`CLUB_NUMB`,`VOTE_NUMB`),
  CONSTRAINT `FK_TM_CLVOTX_03` FOREIGN KEY (`CLUB_NUMB`,`ELCT_NUMB`) REFERENCES `TM_CLOWNX` (`CLUB_NUMB`,`ELCT_NUMB`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 공통 투표';

-- sadari.TB_CLVOPT definition

CREATE TABLE `TB_CLVOPT` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `VOTE_NUMB` bigint NOT NULL COMMENT '모임별 투표 번호',
  `TAGT_NUMB` bigint NOT NULL COMMENT '도서 또는 후보 사용자 대상 번호',
  `TAGT_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '선택지 표시명 스냅샷',
  `OPTI_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '투표 선택지 상태',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`CLUB_NUMB`,`VOTE_NUMB`,`TAGT_NUMB`),
  KEY `IX_TB_CLVOPT_STAT` (`CLUB_NUMB`,`VOTE_NUMB`,`OPTI_STAT`,`TAGT_NUMB`),
  CONSTRAINT `FK_TB_CLVOPT_01` FOREIGN KEY (`CLUB_NUMB`,`VOTE_NUMB`) REFERENCES `TM_CLVOTX` (`CLUB_NUMB`,`VOTE_NUMB`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 투표 선택지';

-- sadari.TB_CLVOTR definition

CREATE TABLE `TB_CLVOTR` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `VOTE_NUMB` bigint NOT NULL COMMENT '모임별 투표 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '투표 시작 시점 유권자 사용자 번호 스냅샷',
  `ELIG_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Y' COMMENT '현재 투표 자격 여부',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`CLUB_NUMB`,`VOTE_NUMB`,`USER_NUMB`),
  CONSTRAINT `CK_TB_CLVOTR_ELIG` CHECK (`ELIG_YSNO` IN ('Y','N')),
  CONSTRAINT `FK_TB_CLVOTR_01` FOREIGN KEY (`CLUB_NUMB`,`VOTE_NUMB`) REFERENCES `TM_CLVOTX` (`CLUB_NUMB`,`VOTE_NUMB`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 투표 유권자 명부';

-- sadari.TB_CLVBAL definition

CREATE TABLE `TB_CLVBAL` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `VOTE_NUMB` bigint NOT NULL COMMENT '모임별 투표 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '유권자 사용자 번호 스냅샷',
  `TAGT_NUMB` bigint NOT NULL COMMENT '선택한 도서 또는 후보 사용자 대상 번호',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`CLUB_NUMB`,`VOTE_NUMB`,`USER_NUMB`),
  KEY `IX_TB_CLVBAL_RSLT` (`CLUB_NUMB`,`VOTE_NUMB`,`TAGT_NUMB`),
  CONSTRAINT `FK_TB_CLVBAL_01` FOREIGN KEY (`CLUB_NUMB`,`VOTE_NUMB`,`USER_NUMB`) REFERENCES `TB_CLVOTR` (`CLUB_NUMB`,`VOTE_NUMB`,`USER_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_CLVBAL_02` FOREIGN KEY (`CLUB_NUMB`,`VOTE_NUMB`,`TAGT_NUMB`) REFERENCES `TB_CLVOPT` (`CLUB_NUMB`,`VOTE_NUMB`,`TAGT_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 유권자별 투표용지';

CREATE TABLE `TM_CLRNDX` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `ROND_NUMB` bigint NOT NULL COMMENT '모임별 회차 번호',
  `BOOK_NUMB` bigint NOT NULL COMMENT '도서 번호',
  `ROND_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '회차 상태',
  `GOAL_STDT` datetime(6) NOT NULL COMMENT '공동 목표 시작 일시',
  `GOAL_ENDT` datetime(6) NOT NULL COMMENT '공동 목표 종료 일시',
  `OPEN_DATE` datetime(6) DEFAULT NULL COMMENT '독후감 공개 일시',
  `COMP_DATE` datetime(6) DEFAULT NULL COMMENT '회차 완료 일시',
  `IDEM_KEYX` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '회차 멱등키',
  `REGI_USER` bigint DEFAULT NULL COMMENT '등록 사용자 번호',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`CLUB_NUMB`,`ROND_NUMB`),
  UNIQUE KEY `UK_TM_CLRNDX_IDEM` (`CLUB_NUMB`,`IDEM_KEYX`),
  KEY `IX_TM_CLRNDX_STAT` (`CLUB_NUMB`,`ROND_STAT`,`GOAL_ENDT`),
  KEY `IX_TM_CLRNDX_BOOK` (`BOOK_NUMB`,`CLUB_NUMB`,`ROND_NUMB`),
  KEY `FK_TM_CLRNDX_REGI` (`REGI_USER`),
  CONSTRAINT `FK_TM_CLRNDX_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TM_CLRNDX_02` FOREIGN KEY (`BOOK_NUMB`) REFERENCES `TM_BKINFO` (`BOOK_NUMB`),
  CONSTRAINT `FK_TM_CLRNDX_03` FOREIGN KEY (`REGI_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 회차';

-- sadari.TM_CLSELT definition

CREATE TABLE `TM_CLSELT` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `SELT_NUMB` bigint NOT NULL COMMENT '모임별 도서 선정 번호',
  `ROND_NUMB` bigint DEFAULT NULL COMMENT '선정 기준 회차 번호',
  `BOOK_SELT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '도서 선정 상태',
  `BOOK_NUMB` bigint DEFAULT NULL COMMENT '최종 선정 도서 번호',
  `DUTY_STDT` datetime(6) DEFAULT NULL COMMENT '모임장 도서 확정 책임 시작 일시',
  `DUTY_ENDT` datetime(6) DEFAULT NULL COMMENT '모임장 도서 확정 책임 마감 일시',
  `PAUS_STDT` datetime(6) DEFAULT NULL COMMENT '책임 기간 일시중지 시작 일시',
  `REMA_SECO` int DEFAULT NULL COMMENT '일시중지 시 남은 책임 시간 초',
  `SELT_DATE` datetime(6) DEFAULT NULL COMMENT '도서 선정 완료 일시',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`CLUB_NUMB`,`SELT_NUMB`),
  UNIQUE KEY `UK_TM_CLSELT_ROND` (`CLUB_NUMB`,`ROND_NUMB`),
  KEY `IX_TM_CLSELT_DUTY` (`CLUB_NUMB`,`BOOK_SELT`,`DUTY_ENDT`),
  KEY `FK_TM_CLSELT_BOOK` (`BOOK_NUMB`),
  CONSTRAINT `CK_TM_CLSELT_REMA` CHECK (`REMA_SECO` IS NULL OR `REMA_SECO` >= 0),
  CONSTRAINT `FK_TM_CLSELT_01` FOREIGN KEY (`CLUB_NUMB`) REFERENCES `TM_CLUBXM` (`CLUB_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TM_CLSELT_02` FOREIGN KEY (`CLUB_NUMB`,`ROND_NUMB`) REFERENCES `TM_CLRNDX` (`CLUB_NUMB`,`ROND_NUMB`),
  CONSTRAINT `FK_TM_CLSELT_03` FOREIGN KEY (`BOOK_NUMB`) REFERENCES `TM_BKINFO` (`BOOK_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 도서 선정 마스터';

ALTER TABLE `TM_CLOWNX`
  ADD KEY `FK_TM_CLOWNX_SELT` (`CLUB_NUMB`,`SELT_NUMB`),
  ADD CONSTRAINT `FK_TM_CLOWNX_04` FOREIGN KEY (`CLUB_NUMB`,`SELT_NUMB`) REFERENCES `TM_CLSELT` (`CLUB_NUMB`,`SELT_NUMB`);

ALTER TABLE `TM_CLVOTX`
  ADD CONSTRAINT `FK_TM_CLVOTX_04` FOREIGN KEY (`CLUB_NUMB`,`SELT_NUMB`) REFERENCES `TM_CLSELT` (`CLUB_NUMB`,`SELT_NUMB`) ON DELETE CASCADE;


-- sadari.TB_CLPART definition

CREATE TABLE `TB_CLPART` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `ROND_NUMB` bigint NOT NULL COMMENT '모임별 회차 번호',
  `PART_NUMB` bigint NOT NULL COMMENT '모임 회차별 참여 번호',
  `USER_NUMB` bigint DEFAULT NULL COMMENT '회차 참여 사용자 번호',
  `REPT_NUMB` bigint DEFAULT NULL COMMENT '연결 독후감 번호',
  `GOAL_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '회차 목표 달성 여부',
  `ACHV_DATE` datetime(6) DEFAULT NULL COMMENT '목표 달성 확정 일시',
  `ANON_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '비식별 참여 여부',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL COMMENT '수정 일시',
  PRIMARY KEY (`CLUB_NUMB`,`ROND_NUMB`,`PART_NUMB`),
  UNIQUE KEY `UK_TB_CLPART_USER` (`CLUB_NUMB`,`ROND_NUMB`,`USER_NUMB`),
  UNIQUE KEY `UK_TB_CLPART_REPT` (`REPT_NUMB`),
  KEY `IX_TB_CLPART_GOAL` (`CLUB_NUMB`,`ROND_NUMB`,`GOAL_YSNO`),
  KEY `FK_TB_CLPART_USER` (`USER_NUMB`),
  CONSTRAINT `FK_TB_CLPART_01` FOREIGN KEY (`CLUB_NUMB`, `ROND_NUMB`) REFERENCES `TM_CLRNDX` (`CLUB_NUMB`, `ROND_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TB_CLPART_02` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL,
  CONSTRAINT `FK_TB_CLPART_03` FOREIGN KEY (`REPT_NUMB`) REFERENCES `TM_REPORT` (`REPT_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 회차 참여';

-- sadari.TH_CLRSLT definition

CREATE TABLE `TH_CLRSLT` (
  `CLUB_NUMB` bigint NOT NULL COMMENT '모임 번호',
  `ROND_NUMB` bigint NOT NULL COMMENT '모임별 회차 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '결과 확인 대상 사용자 번호',
  `REGI_DATE` datetime(6) NOT NULL COMMENT '결과 안내 등록 일시',
  `CONF_DATE` datetime(6) DEFAULT NULL COMMENT '사용자 확인 일시',
  PRIMARY KEY (`CLUB_NUMB`,`ROND_NUMB`,`USER_NUMB`),
  KEY `IX_TH_CLRSLT_USER_CONF` (`USER_NUMB`,`CONF_DATE`,`CLUB_NUMB`,`ROND_NUMB`),
  CONSTRAINT `FK_TH_CLRSLT_01` FOREIGN KEY (`CLUB_NUMB`,`ROND_NUMB`) REFERENCES `TM_CLRNDX` (`CLUB_NUMB`,`ROND_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TH_CLRSLT_02` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='독서 모임 회차 결과 확인 이력';


-- sadari.TH_CMEVDC definition

CREATE TABLE `TH_CMEVDC` (
  `EVDC_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '신고 증거 번호',
  `TAGT_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '신고 대상 유형 세부코드',
  `TAGT_NUMB` bigint NOT NULL COMMENT '신고 대상 번호',
  `TAGT_HASH` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '신고 대상 버전 SHA-256 해시',
  `TAGT_USER` bigint DEFAULT NULL COMMENT '신고 대상 소유 사용자 번호',
  `ORIG_NAME` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '증거 원본 파일명',
  `MIME_TYPE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '증거 파일 MIME 유형',
  `FILE_SIZE` bigint NOT NULL COMMENT '증거 파일 크기 바이트',
  `EVDC_DATA` longblob NOT NULL COMMENT '비공개 신고 증거 원본 바이트',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  PRIMARY KEY (`EVDC_NUMB`),
  UNIQUE KEY `UK_TH_CMEVDC_TAGT_HASH` (`TAGT_TYPE`,`TAGT_NUMB`,`TAGT_HASH`),
  KEY `IX_TH_CMEVDC_TAGT_USER` (`TAGT_USER`,`REGI_DATE`,`EVDC_NUMB`),
  CONSTRAINT `FK_TH_CMEVDC_TAGT_USER` FOREIGN KEY (`TAGT_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='관리자 전용 신고 이미지 증거 원본';


-- sadari.TH_CMPLNT definition

CREATE TABLE `TH_CMPLNT` (
  `CMPL_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '신고 번호',
  `USER_NUMB` bigint DEFAULT NULL COMMENT '신고자 사용자 번호',
  `TAGT_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '신고 대상 유형 세부코드',
  `TAGT_NUMB` bigint NOT NULL COMMENT '신고 대상 번호',
  `TAGT_HASH` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '신고 대상 버전 SHA-256 해시',
  `TAGT_USER` bigint DEFAULT NULL COMMENT '신고 대상 소유 사용자 번호',
  `TAGT_CNTN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '신고 대상 내용 스냅샷',
  `EVDC_NUMB` bigint DEFAULT NULL COMMENT '비공개 신고 이미지 증거 번호',
  `CMPL_RSON` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '신고 사유 세부코드',
  `CMPL_CNTN` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '신고 상세 내용',
  `CMPL_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'CMPL_RECEIVED' COMMENT '신고 처리 상태 세부코드',
  `PROC_CNTN` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '관리자 처리 내용',
  `PROC_ADMN` bigint DEFAULT NULL COMMENT '처리 관리자 번호',
  `PROC_DATE` datetime(6) DEFAULT NULL COMMENT '처리 일시',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 일시',
  PRIMARY KEY (`CMPL_NUMB`),
  UNIQUE KEY `UK_TH_CMPLNT_USER_TAGT` (`USER_NUMB`,`TAGT_TYPE`,`TAGT_NUMB`,`TAGT_HASH`),
  KEY `IX_TH_CMPLNT_TAGT` (`TAGT_TYPE`,`TAGT_NUMB`,`TAGT_HASH`,`CMPL_STAT`,`REGI_DATE`),
  KEY `IX_TH_CMPLNT_TAGT_USER` (`TAGT_USER`,`REGI_DATE`,`CMPL_NUMB`),
  KEY `IX_TH_CMPLNT_USER` (`USER_NUMB`,`REGI_DATE`),
  KEY `IX_TH_CMPLNT_STAT` (`CMPL_STAT`,`REGI_DATE`,`CMPL_NUMB`),
  KEY `FK_TH_CMPLNT_PROC` (`PROC_ADMN`),
  KEY `FK_TH_CMPLNT_EVDC` (`EVDC_NUMB`),
  CONSTRAINT `FK_TH_CMPLNT_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL,
  CONSTRAINT `FK_TH_CMPLNT_TAGT_USER` FOREIGN KEY (`TAGT_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL,
  CONSTRAINT `FK_TH_CMPLNT_EVDC` FOREIGN KEY (`EVDC_NUMB`) REFERENCES `TH_CMEVDC` (`EVDC_NUMB`) ON DELETE SET NULL,
  CONSTRAINT `FK_TH_CMPLNT_PROC` FOREIGN KEY (`PROC_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 신고 접수와 처리 이력';

-- sadari.TH_CMREVT definition

CREATE TABLE `TH_CMREVT` (
  `EVNT_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '신고 조치 안내 이벤트 번호',
  `ACTN_NUMB` bigint DEFAULT NULL COMMENT '자동 조치 결과 번호',
  `TRIG_CMPL` bigint DEFAULT NULL COMMENT '조치 기준 신고 번호',
  `TAGT_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '신고 대상 유형 세부코드',
  `TAGT_NUMB` bigint NOT NULL COMMENT '신고 대상 번호',
  `TAGT_HASH` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '신고 대상 버전 SHA-256 해시',
  `TAGT_USER` bigint DEFAULT NULL COMMENT '피신고 사용자 번호',
  `TAGT_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '신고 대상 유형 표시명 스냅샷',
  `TAGT_ENNM` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '신고 대상 유형 영문 표시명 스냅샷',
  `RSON_SUMM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '피신고자 신고 유형 요약 코드',
  `RSON_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '단일 신고 사유 세부코드',
  `RSON_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '피신고자 신고 유형 표시명 스냅샷',
  `RSON_ENNM` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '피신고자 신고 유형 영문 표시명 스냅샷',
  `ACTN_TYPE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '신고 조치 유형 코드',
  `RPTR_CNTN` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '신고자용 처리 결과 내용',
  `RPTR_ENCT` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '신고자용 영문 처리 결과 내용',
  `TGTR_CNTN` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '피신고자용 조치 안내 내용',
  `TGTR_ENCT` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '피신고자용 영문 조치 안내 내용',
  `PROC_DATE` datetime(6) NOT NULL COMMENT '신고 조치 완료 일시',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '안내 이벤트 등록 일시',
  PRIMARY KEY (`EVNT_NUMB`),
  KEY `IX_TH_CMREVT_ACTN` (`ACTN_NUMB`),
  KEY `IX_TH_CMREVT_TRIG` (`TRIG_CMPL`),
  KEY `IX_TH_CMREVT_TAGT_USER` (`TAGT_USER`,`PROC_DATE`,`EVNT_NUMB`),
  CONSTRAINT `FK_TH_CMREVT_TRIG` FOREIGN KEY (`TRIG_CMPL`) REFERENCES `TH_CMPLNT` (`CMPL_NUMB`) ON DELETE SET NULL,
  CONSTRAINT `FK_TH_CMREVT_TAGT_USER` FOREIGN KEY (`TAGT_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='신고 조치 사용자 안내 이벤트 이력';

-- sadari.TH_CMRSLT definition

CREATE TABLE `TH_CMRSLT` (
  `RSLT_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '신고 조치 결과 확인 번호',
  `EVNT_NUMB` bigint NOT NULL COMMENT '신고 조치 안내 이벤트 번호',
  `CMPL_NUMB` bigint NOT NULL COMMENT '수신자 연결 기준 신고 번호',
  `USER_NUMB` bigint NOT NULL COMMENT '결과 확인 대상 사용자 번호',
  `RCVR_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '결과 수신자 유형 코드',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '결과 안내 등록 일시',
  `CONF_DATE` datetime(6) DEFAULT NULL COMMENT '사용자 확인 일시',
  PRIMARY KEY (`RSLT_NUMB`),
  UNIQUE KEY `UK_TH_CMRSLT_EVNT_RCVR` (`EVNT_NUMB`,`CMPL_NUMB`,`RCVR_TYPE`,`USER_NUMB`),
  KEY `IX_TH_CMRSLT_USER_CONF` (`USER_NUMB`,`CONF_DATE`,`RSLT_NUMB`),
  KEY `IX_TH_CMRSLT_CMPL` (`CMPL_NUMB`),
  CONSTRAINT `FK_TH_CMRSLT_EVNT` FOREIGN KEY (`EVNT_NUMB`) REFERENCES `TH_CMREVT` (`EVNT_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TH_CMRSLT_CMPL` FOREIGN KEY (`CMPL_NUMB`) REFERENCES `TH_CMPLNT` (`CMPL_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_TH_CMRSLT_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='신고 조치 이벤트 수신자별 확인 이력';

-- sadari.TH_CMACTN definition

CREATE TABLE `TH_CMACTN` (
  `ACTN_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '자동 조치 결과 번호',
  `TAGT_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '신고 대상 유형 세부코드',
  `TAGT_NUMB` bigint NOT NULL COMMENT '신고 대상 번호',
  `TAGT_HASH` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '신고 대상 버전 SHA-256 해시',
  `TAGT_USER` bigint DEFAULT NULL COMMENT '신고 대상 소유 사용자 번호',
  `ACTN_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '자동 조치 유형 세부코드',
  `RSLT_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '자동 조치 결과 세부코드',
  `THRS_CNTT` int NOT NULL COMMENT '자동 조치 임계 신고 건수',
  `CMPL_CNTT` int NOT NULL COMMENT '조치 시점 유효 누적 신고 건수',
  `ACTN_ORDR` int NOT NULL COMMENT '동일 대상 자동 조치 순번',
  `TRIG_CMPL` bigint DEFAULT NULL COMMENT '자동 조치 발생 신고 번호',
  `RSLT_CNTN` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '자동 조치 결과 내용',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  PRIMARY KEY (`ACTN_NUMB`),
  UNIQUE KEY `UK_TH_CMACTN_TAGT_ORDR` (`TAGT_TYPE`,`TAGT_NUMB`,`TAGT_HASH`,`ACTN_ORDR`),
  KEY `IX_TH_CMACTN_TAGT_USER` (`TAGT_USER`,`REGI_DATE`,`ACTN_NUMB`),
  KEY `IX_TH_CMACTN_TRIG` (`TRIG_CMPL`),
  CONSTRAINT `FK_TH_CMACTN_TAGT_USER` FOREIGN KEY (`TAGT_USER`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL,
  CONSTRAINT `FK_TH_CMACTN_TRIG` FOREIGN KEY (`TRIG_CMPL`) REFERENCES `TH_CMPLNT` (`CMPL_NUMB`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='신고 누적 자동 조치 결과 이력';

-- sadari.CT_INQURY definition

CREATE TABLE `CT_INQURY` (
  `INQR_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '고객문의 번호',
  `USER_NUMB` bigint DEFAULT NULL COMMENT '문의 작성 사용자 번호',
  `INQR_CATG` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '고객문의 카테고리 세부코드',
  `INQR_TITL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '고객문의 제목',
  `INQR_CNTN` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '고객문의 내용',
  `INQR_STAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'INQR_RECEIVED' COMMENT '고객문의 처리 상태 세부코드',
  `SPND_NUMB` bigint DEFAULT NULL COMMENT '문의와 연결된 이용정지 이력 번호',
  `ASGN_ADMN` bigint DEFAULT NULL COMMENT '담당 관리자 번호',
  `ANSW_DATE` datetime(6) DEFAULT NULL COMMENT '최종 답변 일시',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  `UPDT_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 일시',
  PRIMARY KEY (`INQR_NUMB`),
  KEY `IX_CT_INQURY_USER` (`USER_NUMB`,`REGI_DATE`,`INQR_NUMB`),
  KEY `IX_CT_INQURY_STAT` (`INQR_STAT`,`REGI_DATE`,`INQR_NUMB`),
  KEY `IX_CT_INQURY_SPND` (`SPND_NUMB`,`INQR_STAT`),
  KEY `FK_CT_INQURY_ADMN` (`ASGN_ADMN`),
  CONSTRAINT `FK_CT_INQURY_USER` FOREIGN KEY (`USER_NUMB`) REFERENCES `TM_USERXM` (`USER_NUMB`) ON DELETE SET NULL,
  CONSTRAINT `FK_CT_INQURY_SPND` FOREIGN KEY (`SPND_NUMB`) REFERENCES `TH_USSPND` (`SPND_NUMB`),
  CONSTRAINT `FK_CT_INQURY_ADMN` FOREIGN KEY (`ASGN_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='고객문의 접수와 처리 상태';

-- sadari.CT_INQANS definition

CREATE TABLE `CT_INQANS` (
  `ANSW_NUMB` bigint NOT NULL AUTO_INCREMENT COMMENT '고객문의 답변 번호',
  `INQR_NUMB` bigint NOT NULL COMMENT '고객문의 번호',
  `ANSW_CNTN` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '관리자 답변 내용',
  `READ_YSNO` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'N' COMMENT '사용자 답변 읽음 여부',
  `READ_DATE` datetime(6) DEFAULT NULL COMMENT '사용자 답변 읽음 일시',
  `REGI_ADMN` bigint NOT NULL COMMENT '답변 등록 관리자 번호',
  `REGI_DATE` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '등록 일시',
  PRIMARY KEY (`ANSW_NUMB`),
  KEY `IX_CT_INQANS_INQR` (`INQR_NUMB`,`REGI_DATE`,`ANSW_NUMB`),
  KEY `FK_CT_INQANS_ADMN` (`REGI_ADMN`),
  CONSTRAINT `FK_CT_INQANS_INQR` FOREIGN KEY (`INQR_NUMB`) REFERENCES `CT_INQURY` (`INQR_NUMB`) ON DELETE CASCADE,
  CONSTRAINT `FK_CT_INQANS_ADMN` FOREIGN KEY (`REGI_ADMN`) REFERENCES `TM_ADMINX` (`ADMN_NUMB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='고객문의 관리자 답변';
