-- Sadari 사용자 데이터 전체 초기화
-- 주의: 관리자 기준정보 9개 테이블은 보존하고 사용자·콘텐츠·이력 데이터만 삭제함

SET NAMES utf8mb4;
USE sadari;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `TB_ALIMXX`;
TRUNCATE TABLE `TB_EVTBOX`;
TRUNCATE TABLE `TB_FOLLOW`;
TRUNCATE TABLE `TB_LIKEXX`;
TRUNCATE TABLE `TB_LOGHIS`;
TRUNCATE TABLE `TB_NKSEQX`;
TRUNCATE TABLE `TB_PSHSUB`;
TRUNCATE TABLE `TB_REPLXX`;
TRUNCATE TABLE `TH_CMACTN`;
TRUNCATE TABLE `TH_CMPLNT`;
TRUNCATE TABLE `TH_CMEVDC`;
TRUNCATE TABLE `TH_USSPND`;
TRUNCATE TABLE `TH_USWTHD`;
TRUNCATE TABLE `TL_SCFAIL`;
TRUNCATE TABLE `TL_SCLOGX`;
TRUNCATE TABLE `TM_GOALXM`;
TRUNCATE TABLE `TB_REPTRN`;
TRUNCATE TABLE `TM_REPORT`;
TRUNCATE TABLE `TM_BKINFO`;
TRUNCATE TABLE `TM_USERXM`;
TRUNCATE TABLE `TM_FILEXM`;

-- MySQL에서 Oracle 시퀀스를 대신하는 AUTO_INCREMENT 시작값을 1로 명시함
ALTER TABLE `TB_EVTBOX` AUTO_INCREMENT = 1;
ALTER TABLE `TB_LOGHIS` AUTO_INCREMENT = 1;
ALTER TABLE `TB_REPLXX` AUTO_INCREMENT = 1;
ALTER TABLE `TH_CMACTN` AUTO_INCREMENT = 1;
ALTER TABLE `TH_CMPLNT` AUTO_INCREMENT = 1;
ALTER TABLE `TH_CMEVDC` AUTO_INCREMENT = 1;
ALTER TABLE `TL_SCLOGX` AUTO_INCREMENT = 1;
ALTER TABLE `TM_BKINFO` AUTO_INCREMENT = 1;
ALTER TABLE `TH_USWTHD` AUTO_INCREMENT = 1;
ALTER TABLE `TM_FILEXM` AUTO_INCREMENT = 1;
ALTER TABLE `TM_REPORT` AUTO_INCREMENT = 1;
ALTER TABLE `TM_USERXM` AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
